apiVersion: v1
kind: Service
metadata:
  name: {{ template "myjenkins.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.service.port }}
